import type { RawMesh } from '../geometry/mesh.ts';

const HEADER_BYTES = 80;
const TRIANGLE_BYTES = 50;

/**
 * Serializes a mesh as binary STL (little-endian). Coordinates are emitted
 * as-is; the mesh is modeled in mm and slicers interpret STL units as mm.
 * Facet normals are computed from the CCW winding, which Manifold guarantees
 * to face outward.
 */
export function writeBinaryStl(mesh: RawMesh): ArrayBuffer {
  const { positions, indices } = mesh;
  const triangleCount = indices.length / 3;
  const buffer = new ArrayBuffer(HEADER_BYTES + 4 + triangleCount * TRIANGLE_BYTES);
  const view = new DataView(buffer);
  const headerText = 'Binary STL generated by basemaker. Units: mm.';
  for (let i = 0; i < Math.min(headerText.length, HEADER_BYTES); i++) {
    view.setUint8(i, headerText.charCodeAt(i));
  }
  view.setUint32(HEADER_BYTES, triangleCount, true);

  let offset = HEADER_BYTES + 4;
  for (let t = 0; t < triangleCount; t++) {
    const ia = indices[t * 3] * 3;
    const ib = indices[t * 3 + 1] * 3;
    const ic = indices[t * 3 + 2] * 3;
    const abx = positions[ib] - positions[ia];
    const aby = positions[ib + 1] - positions[ia + 1];
    const abz = positions[ib + 2] - positions[ia + 2];
    const acx = positions[ic] - positions[ia];
    const acy = positions[ic + 1] - positions[ia + 1];
    const acz = positions[ic + 2] - positions[ia + 2];
    let nx = aby * acz - abz * acy;
    let ny = abz * acx - abx * acz;
    let nz = abx * acy - aby * acx;
    const length = Math.hypot(nx, ny, nz);
    if (length > 0) {
      nx /= length;
      ny /= length;
      nz /= length;
    }
    view.setFloat32(offset, nx, true);
    view.setFloat32(offset + 4, ny, true);
    view.setFloat32(offset + 8, nz, true);
    for (const index of [ia, ib, ic]) {
      offset += 12;
      view.setFloat32(offset, positions[index], true);
      view.setFloat32(offset + 4, positions[index + 1], true);
      view.setFloat32(offset + 8, positions[index + 2], true);
    }
    offset += 12 + 2;
    view.setUint16(offset - 2, 0, true);
  }
  return buffer;
}
